"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Preview mode is read at mount; these links intentionally reload the document. */
import React,{useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Toaster,toast} from 'sonner';
import {Leaf,Search,ShoppingBag,ArrowUpRight,ArrowRight,ArrowLeft,Check,ShieldCheck,MapPin,Heart,Plus,Minus,Play,Pause,Mic,Camera,Upload,Trash2,Copy,Package,Truck,Wallet,Users,Home,Grid2X2,UserRound,Bell,ChevronDown,X,Volume2,SlidersHorizontal,CheckCircle2,Clock,WifiOff,TriangleAlert,RotateCcw,Send,ScanLine,BarChart3,LogOut,Loader2,FileCheck2,Landmark,Globe,Sprout,Headphones,Download,Layers,MessageSquare,Star,Boxes} from 'lucide-react';
import {PortalScreens,ModalContent} from './screens';
import LiveMarket from './live-market';
import PublishedCrafts from './published-crafts';
import {CraftFilm} from './craft-film';
import {AuthScreen} from './auth-screen';
import {AuthSession,getCurrentSession,onAuthStateChange,signOut as supabaseSignOut} from '@/lib/auth';
import {API_URL} from '@/lib/api';
import LanguageSelector from '@/components/language-selector';
export type Role='buyer'|'artisan'|'ambassador';
export const products=[
{id:'basket',title:'Wild Grass Smoked Bamboo Basket',maker:'Devki Bai Marawi',region:'Mandla Forest Ridge, Madhya Pradesh',category:'Bamboo & cane',price:1250,photo:'/basket.png',rating:'4.9',material:'River bamboo, wild forest grass, mustard seed oil'},
{id:'vase',title:'Earth & Ember Clay Vase',maker:'Meera Kumhar',region:'Kondagaon, Chhattisgarh',category:'Terracotta clay',price:890,photo:'/vase.png',rating:'4.8',material:'Natural terracotta clay'},
{id:'throw',title:'Forest Stripe Handwoven Throw',maker:'Lata Markam',region:'Bastar, Chhattisgarh',category:'Tribal handloom',price:1800,photo:'/throw.png',rating:'4.9',material:'Handspun cotton'},
{id:'dokra',title:'Dokra Forest Deer',maker:'Ramesh Baghel',region:'Kondagaon, Chhattisgarh',category:'Dokra bell metal',price:1950,photo:'/dokra.png',rating:'4.9',material:'Bell metal, lost-wax casting'},
{id:'iron',title:'Bastar Iron Candle Stand',maker:'Soma Netam',region:'Bastar, Chhattisgarh',category:'Bastar wrought iron',price:1450,photo:'/iron.png',rating:'4.8',material:'Hand-forged iron'},
{id:'forest',title:'Forest Botanical Keepsake',maker:'Anita Tekam',region:'Mandla, Madhya Pradesh',category:'Forest foraged goods',price:650,photo:'/forest.png',rating:'4.7',material:'Dried forest botanicals, glass'}];
export const money=(v:number)=>'₹'+v.toLocaleString('en-IN');
export const titles=['Photograph your craft','Enhance the photo','Identify category and materials','Measure dimensions','Record and review your story','Set a fair price','Review the listing','Field review and publish'];
export const stepNames=['Photos','Enhance','Identify','Dimensions','Voice','Price','Listing','Publish'];
export const delivery=['Confirmed','Processing','Ready to Ship','Shipped','Delivered'];
export const initial={title:products[0].title,material:products[0].material,dimensions:'32 × 32 × 18 cm',price:1250,transcript:'I weave this basket using river bamboo and wild forest grass. It takes two days to shape, smoke, and finish by hand with mustard seed oil.',language:'English',status:'Live',verified:true,confidence:96,inspection:[true,true,true,true],notes:'Materials and dimensions confirmed in person with Devki. The natural oil finish and handwoven variation match the maker’s description.',fieldAudio:true,order:true,orderStage:3,orderQty:1,orderPrice:1250,qty:1,wallet:1137,payout:'available',saved:['basket','throw'] as string[],photos:['/basket.png','/basket.png','/basket.png','/basket.png'],quote:true,quoteData:{organization:'Canopy House',category:'Bamboo & cane',quantity:40,budget:50000,destination:'Bengaluru, Karnataka',requirements:'Natural finish, consistent dimensions, no plastic packaging.'},photoState:'completed',draft:false};
export const roleName={buyer:'Buyer',artisan:'Artisan',ambassador:'Field Ambassador'};
export const views=[{role:'buyer',id:'home',name:'Discovery home'},{role:'buyer',id:'categories',name:'Craft categories'},{role:'buyer',id:'compare',name:'Compare crafts'},{role:'buyer',id:'map',name:'Artisan map'},{role:'buyer',id:'customize',name:'Made-to-order request'},{role:'buyer',id:'messages',name:'Buyer messages'},{role:'buyer',id:'product',name:'Product detail'},{role:'buyer',id:'cart',name:'Cart drawer'},{role:'buyer',id:'checkout',name:'Checkout'},{role:'buyer',id:'success',name:'Payment and order success'},{role:'buyer',id:'orders',name:'Buyer orders'},{role:'buyer',id:'bulk',name:'Bulk B2B sourcing'},{role:'buyer',id:'profile',name:'Buyer profile'},{role:'artisan',id:'home',name:'Artisan dashboard'},...titles.map((n,i)=>({role:'artisan',id:'step-'+(i+1),name:String(i+1).padStart(2,'0')+' · '+n})),{role:'artisan',id:'orders',name:'Artisan orders'},{role:'artisan',id:'wallet',name:'Artisan wallet'},{role:'artisan',id:'guild',name:'Artisan guild and network QR'},{role:'artisan',id:'messages',name:'Artisan messages'},{role:'ambassador',id:'home',name:'Ambassador home'},{role:'ambassador',id:'verification',name:'Verification queue'},{role:'ambassador',id:'inspect',name:'Full field verification'},{role:'ambassador',id:'visits',name:'Visit planner'},{role:'ambassador',id:'feedback',name:'Feedback'},{role:'ambassador',id:'reviews',name:'Reviews'},{role:'ambassador',id:'messages',name:'Ambassador messages'},{role:'ambassador',id:'profile',name:'Profile'},{role:'ambassador',id:'network',name:'Field network and guild'},{role:'ambassador',id:'reports',name:'Reports and analytics'}];
export const states=['Default','Loading','Empty','Offline','Error','Disabled','Partial','Success','Recording','Paused','Completed','Uploading','Replace','Delete','Low stock','Sold out','Payment failure','Delayed','Incomplete','Rejected','Urgent','Transfer initiated','Transfer success','Search empty','Quote success','Payment loading','Submitting','Processing'];
export function Btn({children,tone='primary',className='',...props}:React.ComponentProps<typeof Button>&{tone?:string}){return <Button variant={tone==='primary'?'default':tone==='ghost'?'ghost':'outline'} className={'jm-btn '+tone+' '+className} {...props}>{children}</Button>}
export function Badge({children,tone='green',className='',style,...props}:React.HTMLAttributes<HTMLSpanElement>&{tone?:string}){return <span className={'badge '+tone+' '+(className||'')} style={style} {...props}>{children}</span>}
export function Panel({children,className='',...props}:React.HTMLAttributes<HTMLDivElement>){return <section className={'panel '+className} {...props}>{children}</section>}
export function Field({label,children,hint}:{label:string,children:React.ReactNode,hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Empty({title,detail,action,onClick,icon:Icon=Package}:{title:string,detail:string,action?:string,onClick?:()=>void,icon?:typeof Package}){return <div className="empty" data-component="Empty state"><span className="empty-icon"><Icon size={32}/></span><h2>{title}</h2><p>{detail}</p>{action&&<Btn onClick={onClick}>{action}<ArrowRight size={18}/></Btn>}</div>}
export function AudioStory({label='Hear Devki’s story',text=initial.transcript}:{label?:string,text?:string}){const [playing,setPlaying]=useState(false);useEffect(()=>()=>{if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel()},[]);function toggle(){if(playing){if('speechSynthesis'in window)speechSynthesis.cancel();setPlaying(false);return}if(!('speechSynthesis'in window)){toast.info('Voice playback isn’t available here. The story transcript is shown below.');return}setPlaying(true);const u=new SpeechSynthesisUtterance(text);u.rate=.86;u.onend=()=>setPlaying(false);speechSynthesis.speak(u)}return <div className={'audio '+(playing?'playing':'')} data-component="Audio controls" data-variant={playing?'Playing':'Idle'}><Btn tone="ghost" aria-label={playing?'Stop story':'Play voice preview'} onClick={toggle}>{playing?<Pause/>:<Play/>}</Btn><div><strong>{label}</strong><span className="wave">{Array.from({length:22},(_,i)=><i key={i} style={{height:6+(i*7%20)+'px',animationDelay:i*.05+'s'}}/>)}</span><small>{playing?'Playing voice preview':'Voice preview · English · 0:24'}</small></div><Volume2 size={18}/></div>}
export function Payout({price=1250,qty=1}:{price?:number,qty?:number}){const net=price-113;return <div className="payout" data-component="Payout meter"><div className="row between"><span>Directly to the maker</span><strong>{money(net*qty)}</strong></div><div className="payout-track" aria-label={`${(net/price*100).toFixed(1)} percent paid to artisan`}><i style={{width:net/price*100+'%'}}/><i style={{width:80/price*100+'%'}}/><i style={{width:33/price*100+'%'}}/></div><div className="payout-legend"><span><i/>Artisan <b>{money(net*qty)}</b></span><span><i/>Logistics <b>{money(80*qty)}</b></span><span><i/>Network <b>{money(33*qty)}</b></span></div></div>}
export function Timeline({stage=4,provenance=false}:{stage?:number,provenance?:boolean}){const items=provenance?['Made by Devki','Field verified','ONDC listing','Your doorstep','Maker paid']:delivery;return <ol className="timeline" data-component="Timeline">{items.map((s,i)=><li key={s} className={i<=stage?'done':''}><span>{i<stage?<Check size={14}/>:i+1}</span><div><strong>{s}</strong><small>{provenance?['Mandla · 2 days of handwork','Rajesh Sahu · 96% confidence','One craft, an open network','Tracked, protected delivery','Direct bank settlement'][i]:['Order received','Prepared by the maker','Pickup scheduled','Delhivery · In transit','Delivery confirmed'][i]}</small></div></li>)}</ol>}
export default function JungleMarket(){
const [role,setRole]=useState<Role>('buyer'),[view,setView]=useState('home'),[d,setD]=useState(initial),[ready,setReady]=useState(false),[modal,setModal]=useState(''),[cart,setCart]=useState(false),[state,setState]=useState('Default'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All Stories'),[priceLimit,setPriceLimit]=useState(0),[selected,setSelected]=useState('basket'),[address,setAddress]=useState('Sample House, Forest Road, Bengaluru, Karnataka 560001'),[quoteOrg,setQuoteOrg]=useState('Canopy House'),[busy,setBusy]=useState(false),[showDesign,setShowDesign]=useState(false),[capture,setCapture]=useState(false),[recState,setRecState]=useState('idle'),[offline,setOffline]=useState(false);
const [authSession,setAuthSession]=useState<AuthSession|null>(null),[authReady,setAuthReady]=useState(false);
const fileRef=useRef<HTMLInputElement>(null);const [photoSlot,setPhotoSlot]=useState(0);const p=selected==='basket'?{...products[0],title:d.title,price:d.price,material:d.material}:products.find(p=>p.id===selected)!;
const update=(data:Partial<typeof initial>)=>setD(prev=>({...prev,...data}));
function go(r:Role,v:string){setRole(r);setView(v);setState('Default');setModal('');setCart(v==='cart');location.hash=r+'/'+v;window.scrollTo(0,0)}
function applyAuthSession(session:AuthSession,resetView=false){setAuthSession(session);const accountRole=session.user.role.toLowerCase() as Role;if(resetView)setRole(accountRole);if(resetView){const [hashRole,hashView]=location.hash.slice(1).split('/');setView(hashRole===accountRole&&(views.some(v=>v.role===accountRole&&v.id===hashView)||['reports','messages','orders','profile'].includes(hashView))?hashView:'home')}}
// Initialize browser-only preview state after hydration.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{try{const data=localStorage.getItem('jungle-market-demo-v2');if(data)setD({...initial,...JSON.parse(data)})}catch{}const h=location.hash.slice(1).split('/');if(['buyer','artisan','ambassador'].includes(h[0])){setRole(h[0] as Role);setView(h[1]||'home')}const u=new URLSearchParams(location.search);setCapture(u.has('capture'));setShowDesign(u.has('design'));if(u.get('state'))setState(u.get('state')!);if(u.has('capture')){const fixture={...initial,qty:1,order:true,orderStage:3,wallet:1137,quote:true,photos:['/basket.png','/basket.png','/basket.png','/basket.png'],inspection:[true,true,true,true],fieldAudio:true,notes:'Materials and dimensions confirmed in person with Devki. The natural oil finish and handwoven variation match the maker’s description.'};if(h[0]==='ambassador'||(h[0]==='artisan'&&Number((h[1]||'').split('-')[1])<10)){fixture.verified=false;fixture.status='Review pending'}const stateName=u.get('state');if(stateName==='Empty'){fixture.photos=['','','',''];fixture.qty=0;fixture.wallet=0;fixture.order=false;fixture.quote=false}if(stateName==='Delete')fixture.photos[0]='';if(stateName==='Incomplete'){fixture.inspection=[true,false,false,true];fixture.fieldAudio=false;fixture.notes=''}if(stateName==='Error'&&h[1]==='step-4')fixture.title='';if(stateName==='Error'&&h[1]==='step-5')fixture.price=850;if(h[1]==='step-9'&&['Partial','Error','Disabled'].includes(stateName||'')){fixture.verified=true;fixture.status='Ready to publish'}if(stateName==='Success'&&h[0]==='ambassador'){fixture.verified=true;fixture.status='Live'}if(stateName==='Transfer success'){fixture.wallet=0;fixture.payout='transferred'}if(['Payment loading','Submitting','Processing'].includes(stateName||''))setBusy(true);setD(fixture);setAddress('Sample House, Forest Road, Bengaluru, Karnataka 560001');if(u.get('modal'))setModal(u.get('modal')!);if(h[1]==='cart')setCart(true)}setReady(true);const off=()=>setOffline(!navigator.onLine);window.addEventListener('offline',off);window.addEventListener('online',off);return()=>{window.removeEventListener('offline',off);window.removeEventListener('online',off)}},[]);
useEffect(()=>{if(ready&&capture)try{localStorage.setItem('jungle-market-demo-v2',JSON.stringify(d))}catch{}},[d,ready,capture]);
useEffect(()=>{const handler=()=>{const h=location.hash.slice(1).split('/');if(['buyer','artisan','ambassador'].includes(h[0])){setRole(h[0] as Role);setView(h[1]||'home')}};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[]);

useEffect(()=>{if(!capture)return;const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};register({name:'read_craft_record',title:'Read the connected craft',description:'Read the sample craft, verification, order and payout currently shown in the Jungle Market prototype.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({title:d.title,maker:'Devki Bai Marawi',price:d.price,artisanPayout:d.price-113,status:d.status,verified:d.verified,orderPlaced:d.order,fulfillment:delivery[d.orderStage],wallet:d.wallet,prototype:true})});register({name:'navigate_portal_screen',title:'Open a portal screen',description:'Navigate to an existing screen in the prototype. Does not place orders, publish listings, or transfer funds.',inputSchema:{type:'object',properties:{role:{type:'string',enum:['artisan','ambassador','buyer']},screen:{type:'string'}},required:['role','screen'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{role:Role;screen:string})=>{if(!views.some(v=>v.role===input?.role&&v.id===input?.screen))throw new Error('Unknown portal screen');go(input.role,input.screen);return {role:input.role,screen:input.screen,prototype:true}}});return()=>life.abort()},[d,capture]);
// The preview bypass and session subscription are initialized once after hydration.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{const params=new URLSearchParams(location.search);if(params.has('capture')||params.has('design')){setAuthReady(true);return}let active=true;getCurrentSession().then(session=>{if(!active)return;if(session)applyAuthSession(session,true);else setAuthSession(null)}).catch(()=>{if(active)setAuthSession(null)}).finally(()=>{if(active)setAuthReady(true)});let unsubscribe=()=>{};onAuthStateChange(session=>{if(!active)return;if(session)applyAuthSession(session);else setAuthSession(null);setAuthReady(true)}).then(stop=>{if(active)unsubscribe=stop;else stop()}).catch(()=>{if(active)setAuthReady(true)});return()=>{active=false;unsubscribe()}},[]);
function authenticated(session:AuthSession){history.replaceState(null,'',location.pathname+'#'+session.user.role.toLowerCase()+'/home');applyAuthSession(session,true)}
async function signOut(){try{await supabaseSignOut()}catch(error){toast.error(error instanceof Error?error.message:'Sign out failed. Please retry.');return}setAuthSession(null);setModal('');setCart(false);location.hash='';toast.success('You have been signed out.')}
const add=()=>{if(!d.verified){toast.info('Devki’s craft needs a field signature before checkout.');return}if(selected!=='basket'){toast.info('The connected purchase preview uses Devki’s basket.');setSelected('basket')}update({qty:Math.min(d.qty+1,5)});toast.success('Added to your basket');setCart(true)};
const detail=(id='basket')=>{setSelected(id);go('buyer','product')};
const startPublish=()=>{const url=new URL(location.href);const clearDraft=!view.startsWith('step-')&&url.searchParams.has('draft');update({status:'Draft',draft:true,verified:false});go('artisan','step-1');if(clearDraft){url.searchParams.delete('draft');url.hash='artisan/step-1';history.replaceState(null,'',url);}};
const isEmpty=state==='Empty'||state==='Search empty';
const matches=products.filter(x=>(!priceLimit||(x.id==='basket'?d.price:x.price)<=priceLimit)&&(filter!=='Field Verified'||x.id!=='basket'||d.verified)&&(filter!=='Saved'||d.saved.includes(x.id))&&(filter!=='Listen'&&filter!=='Direct Impact'||x.id==='basket')&&(view!=='search'||!query||/home|story|stories|natural/i.test(query)||(/bastar craft/i.test(query)?x.region.includes('Bastar')||x.region.includes('Chhattisgarh'):[x.title,x.category,x.region,x.maker,x.material].join(' ').toLowerCase().includes(query.toLowerCase()))));
function productCard(item:typeof products[0]){return <article className="product-card" key={item.id} data-component="Product card"><div className="product-photo"><button className="image-button" onClick={()=>detail(item.id)} aria-label={'View '+item.title}><img src={item.id==='basket'&&d.photos[0]?d.photos[0]:item.photo} alt={item.title}/></button><Badge><ShieldCheck size={13}/>{item.id==='basket'&&!d.verified?'In field review':'Field verified'}</Badge><button className={'save '+(d.saved.includes(item.id)?'saved':'')} aria-label={(d.saved.includes(item.id)?'Unsave ':'Save ')+item.title} onClick={()=>update({saved:d.saved.includes(item.id)?d.saved.filter(x=>x!==item.id):[...d.saved,item.id]})}><Heart size={19}/></button></div><div className="product-meta"><span className="eyebrow">{item.category}</span><span>★ {item.rating}</span></div><button className="text-link title-link" onClick={()=>detail(item.id)}>{item.id==='basket'?d.title:item.title}</button><p>by {item.maker}</p><div className="row between"><strong className="price">{money(item.id==='basket'?d.price:item.price)}</strong><Btn tone="ghost" aria-label={'Quick add '+item.title} disabled={item.id==='basket'&&!d.verified} onClick={()=>item.id==='basket'?add():detail(item.id)}><Plus/></Btn></div></article>}
const preview=true; // Keep the established presentation as the default frontend.
const nav:[string,string,typeof Home][] =role==='buyer'?[['home','Discover',Home],['categories','Categories',Layers],['orders','Orders',Package],['bulk','Bulk',Boxes],['profile','You',UserRound]]:role==='artisan'?[['home','My craft',Home],['orders','Orders',Package],['wallet','Wallet',Wallet],['guild','Guild',Users]]:[['home','Home',Home],['verification','Verify',ShieldCheck],['visits','Visits',MapPin],['reports','Reports',BarChart3],['profile','Profile',UserRound]];
if(!authReady)return <div className="auth-loading" role="status"><span><Leaf/></span><p>Opening Jungle Market…</p></div>;
if(!capture&&!new URLSearchParams(location.search).has('design')){
const params=new URLSearchParams(location.search);
if(!authSession&&!params.has('craft')&&!params.has('browse'))return <AuthScreen onAuthenticated={authenticated}/>;
// The original portal is the main interface. The connected workspace is explicit.
if(params.has('workspace')||params.has('craft'))return <LiveMarket session={authSession} onSignOut={signOut}/>;
}
return <div className={'jungle '+(capture?'capture':'')} data-role={role} data-view={view}>
<Toaster theme="light" position="top-center" richColors/><a href="#main" className="skip-link">Skip to content</a>
<header className="topbar"><div className="header-inner"><button className="brand" onClick={()=>go(role,'home')} aria-label="Jungle Market home"><span className="brand-mark"><img src="/favicon.svg" alt="Logo" width="25" height="25" /></span><span>jungle market<small>ROOTED IN PEOPLE</small></span></button><nav className="desktop-nav">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>go(role,id)}>{label}</button>)}</nav><div className="header-actions"><LanguageSelector compact /><button className="role-pill" onClick={()=>preview?setModal('roles'):go(role,'profile')} aria-label={preview?'Switch portal':'Your account'}>{authSession?.user.full_name.split(' ')[0]||(preview?roleName[role]:'Sign in')}<span className="account-role">{roleName[role]}</span><ChevronDown size={15}/></button><Btn tone="ghost" aria-label="Messages" className="header-icon notification-button" onClick={()=>preview?setModal('notifications'):go(role,'messages')}><Bell/></Btn>{role==='buyer'&&<Btn tone="ghost" aria-label={preview?"Open basket":"Your orders"} className="header-icon basket-button" onClick={()=>preview?setCart(true):go(role,"orders")}><ShoppingBag/>{preview&&d.qty>0&&<b>{d.qty}</b>}</Btn>}</div></div></header>

{showDesign&&<aside className="design-controls"><label>Portal<select value={role} onChange={e=>go(e.target.value as Role,'home')}>{Object.entries(roleName).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Screen<select value={view} onChange={e=>go(role,e.target.value)}>{views.filter(v=>v.role===role).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Preview state<select value={state} onChange={e=>setState(e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></label><Btn tone="secondary" onClick={()=>setView('system')}>Design system</Btn><Btn tone="secondary" onClick={()=>setModal('export')}>Figma package<Download size={16}/></Btn></aside>}
{(offline||state==='Offline')&&<div className="notice warning" role="status"><WifiOff/>You’re offline. Your draft is saved on this device. <button onClick={()=>{setState('Default');setOffline(!navigator.onLine)}}>Try again</button></div>}
<main id="main" className={role==='buyer'?'buyer-main':'work-main'}>
{state==='Loading'?<div className="skeleton-page" aria-busy="true" aria-label="Loading your crafts"><div/><div/><div/></div>:<>
{role==='buyer'&&(view==='home'||view==='search')&&<>{view==='home'?<section className="discovery-hero"><div className="hero-copy"><div className="eyebrow"><span/>CRAFT DISCOVERY · MADE HUMAN</div><h1>From Mandla Forest Ridge <em>to your home</em></h1><p>Made by Devki Bai Marawi. River bamboo and wild forest grass, shaped by two days of patient handwork.</p><Btn className="hero-story-cta" onClick={()=>detail()}>Shop this story<ArrowUpRight/></Btn><form className="hero-search" onSubmit={e=>{e.preventDefault();setView('search')}}><Search/><Input aria-label="Search crafts and makers" placeholder="A little nature for my home…" value={query} onChange={e=>setQuery(e.target.value)}/><Btn type="submit" aria-label="Search crafts"><ArrowRight/></Btn></form><div className="suggestions">{['Bastar craft under ₹2,000','Natural home decor','Listen to maker stories'].map(x=><button key={x} onClick={()=>{setQuery(x);setView('search')}}>{x}<ArrowUpRight size={12}/></button>)}</div><div className="hero-foot"><ShieldCheck size={18}/><span>Real makers. Verified roots. Fairer futures.</span></div></div><div className="hero-image film-hero"><CraftFilm variant="hero" alt="Wild Grass Smoked Bamboo Basket, with its warm bamboo rim and diagonal grass weave"/><span className="film-origin">MANDLA FOREST RIDGE</span></div></section>:<section className="search-heading"><button className="back" onClick={()=>go('buyer','home')}><ArrowLeft/>Back to discovery</button><div className="eyebrow">FIND YOUR NEXT STORY</div><h1>{query||'Thoughtfully made, just for you.'}</h1><form className="hero-search" onSubmit={e=>e.preventDefault()}><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search products"/><Btn type="submit" aria-label="Search products"><Search/></Btn></form></section>}
<PublishedCrafts query={view==='search'?query:''}/>{view==='home'&&<section className="featured-story" aria-label="Featured craft"><div><span className="eyebrow">THE CRAFT BEHIND THE STORY</span><h2>{d.title}</h2><p>Made by Devki Bai Marawi</p><Badge tone={d.verified?'green':'amber'}><ShieldCheck size={16}/>{d.verified?'Field verified by Rajesh Sahu':'Field review with Rajesh Sahu'}</Badge></div><div className="featured-story-buy"><strong>{money(d.price-113)} goes directly to the artisan</strong><span>{money(d.price)} · Shipping included</span><Btn onClick={()=>detail()}>Shop this craft<ArrowUpRight/></Btn></div></section>}
<section className="section category-section"><div className="section-title"><h2>Shop by craft</h2><button className="text-link" onClick={()=>go('buyer','categories')}>All crafts<ArrowUpRight size={17}/></button></div><div className="category-rail">{products.map((x,i)=><button key={x.id} onClick={()=>{setQuery(x.category);setView('search')}}><span className="category-circle"><img src={x.photo} alt=""/></span><strong>{x.category}</strong><small>{[24,18,36,21,12,15][i]} stories</small></button>)}</div></section>
<section className="section"><div className="section-title"><div><div className="eyebrow">GOOD THINGS, MADE SLOWLY</div><h2>{view==='search'?'Crafts with a story':'Picked for your home'}</h2></div><Btn tone="secondary" onClick={()=>setModal('filters')}><SlidersHorizontal size={16}/>Filters</Btn></div><div className="filter-tabs">{['All Stories','Field Verified','Listen','Direct Impact'].map(x=><button aria-pressed={filter===x} className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x==='Listen'&&<Headphones size={15}/>} {x}</button>)}</div>{isEmpty||!matches.length?<Empty title="No crafts found yet" detail="Try a material like bamboo, or explore all the maker stories." action="Explore all crafts" onClick={()=>{setState('Default');setQuery('');setFilter('All Stories');setPriceLimit(0)}}/>:<div className="product-grid">{matches.slice(0,view==='home'?4:6).map(productCard)}</div>}</section>
<section className="story-section"><div className="story-visual story-film-visual"><CraftFilm variant="story" alt="The basket’s diagonal weave and natural river-bamboo texture"/><div className="film-acts" aria-label="The three acts of this craft story"><span><b>01</b>The making</span><span><b>02</b>Verification & trust</span><span><b>03</b>At home</span></div></div><div className="story-copy"><div className="eyebrow">NOT JUST A PRODUCT. A PERSON.</div><h2>Know what you<br/><em>bring home.</em></h2><p>Made by Devki Bai Marawi. Field verified by Rajesh Sahu. Follow the materials, the maker’s hands, and the care that brings this craft to your home.</p><AudioStory text={d.transcript}/><Timeline stage={d.order?d.orderStage:2} provenance/><Payout price={d.price}/><button className="text-link" onClick={()=>detail()}>Shop this story<ArrowUpRight/></button></div></section>
<section className="b2b-banner"><div><div className="eyebrow">THOUGHTFUL SPACES BEGIN HERE</div><h2>Sourcing for a shop or hotel?</h2><p>Bring authentic handwork to a bigger canvas. Source directly, at a human scale.</p></div><Btn tone="cream" onClick={()=>go('buyer','bulk')}>Explore bulk sourcing<ArrowUpRight/></Btn></section></>}
<PortalScreens {...{role,view,d,update,go,state,setState,setModal,detail,p,add,isEmpty,startPublish,address,setAddress,busy,setBusy,query,setQuery,recState,setRecState,setPhotoSlot,fileRef,quoteOrg,setQuoteOrg,setFilter,authUser:authSession?.user,authToken:authSession?.access_token}}/>
</>}
</main>
<footer className="site-footer"><div className="brand"><img src="/favicon.svg" alt="Logo" width="25" height="25" />jungle market</div><p>Craft has a place. Its people have a voice.</p><div><span>{preview?'Design preview · sample records':'Maker-supplied facts. Human field review. Stories shared by permission.'}</span><a href="/?design=1#buyer/home">Explore the design</a></div></footer>
<nav className="bottom-nav" aria-label={roleName[role]+' navigation'}>{(role==='artisan'?[...nav.slice(0,2),['sell','Sell',Plus] as [string,string,typeof Home],...nav.slice(2)]:nav).map(([id,label,Icon])=>id==='sell'?<a key={id} href="#artisan/step-1" className="sell-nav" onClick={startPublish}><Icon size={21}/><span>{label}</span></a>:<button key={id} className={view===id?'active':''} onClick={()=>go(role,id)}><Icon size={21}/><span>{label}</span></button>)}</nav>
{!capture&&<Btn className="support-float" tone="primary" aria-label="Messages" onClick={()=>go(role,'messages')}><MessageSquare size={21}/></Btn>}
<input ref={fileRef} hidden type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>15000000){toast.error('Choose a photo smaller than 15 MB.');return}update({photoState:'uploading'});const localUrl=URL.createObjectURL(f);try{const fd=new FormData();fd.append('file',f);fd.append('uploader_user_id','aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee');const res=await fetch(`${API_URL}/v1/media/image`,{method:'POST',body:fd});if(!res.ok)throw new Error('Upload failed');await res.json();const photos=[...d.photos];photos[photoSlot]=localUrl;update({photos,photoState:'completed'});toast.success('Photo uploaded & processed');}catch(err){const photos=[...d.photos];photos[photoSlot]=localUrl;update({photos,photoState:'completed'});toast.success('Photo added locally');}e.target.value=''}}/>
<Sheet open={preview&&cart} onOpenChange={setCart}><SheetContent className="cart-sheet" data-component="Cart drawer"><SheetTitle>Your basket</SheetTitle><SheetDescription>Good things, directly from the people who make them.</SheetDescription>{d.qty===0||isEmpty?<Empty title="A story is waiting for you" detail="Find your first handmade piece and bring a little meaning home." action="Discover crafts" onClick={()=>{setCart(false);go('buyer','home')}} icon={ShoppingBag}/>:<><div className="cart-item"><img src={d.photos[0]||'/basket.png'} alt={d.title}/><div><Badge>Field verified</Badge><h3>{d.title}</h3><small>Devki Bai Marawi · Mandla</small><strong>{money(d.price)}</strong><div className="row"><Btn tone="secondary" aria-label="Decrease quantity" onClick={()=>update({qty:Math.max(0,d.qty-1)})}><Minus/></Btn><b>{d.qty}</b><Btn tone="secondary" aria-label="Increase quantity" disabled={d.qty>=5} onClick={()=>update({qty:d.qty+1})}><Plus/></Btn><Btn tone="ghost" aria-label="Remove basket" onClick={()=>update({qty:0})}><Trash2/></Btn></div></div></div><Payout price={d.price} qty={d.qty}/><div className="cart-bottom"><div className="row between"><span>Subtotal</span><strong>{money(d.price*d.qty)}</strong></div><small>Shipping included. Nothing hidden.</small><Btn onClick={()=>{setCart(false);go('buyer','checkout')}}>Proceed to Secure Checkout<ArrowRight/></Btn><p><ShieldCheck size={16}/>Your purchase supports the named maker.</p></div></>}</SheetContent></Sheet>
<Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('')}}><DialogContent data-component="Dialog" className={'jm-modal '+(modal==='roles'?'role-modal':'')}><DialogTitle>{({roles:'One market. Three perspectives.',notifications:'Your updates',filters:'Find your kind of craft',support:'How can we help?',about:'A connected craft prototype',quote:'Request a sourcing quote',withdraw:'Send earnings to your bank',cancel:'Keep your craft draft?',revise:'Request a thoughtful revision',batch:'Log your batch impact',address:'Your delivery addresses',export:'Your design handoff',reject:'Return listing for revision',certificate:'GI certificate record',qr:'Onboard an artisan',signout:'Sign out of Jungle Market?'} as Record<string,string>)[modal]||'Jungle Market'}</DialogTitle><DialogDescription>{modal==='roles'?'Follow Devki’s basket from the maker to its new home. Your progress stays with it.':'Jungle Market · Connected prototype'}</DialogDescription><ModalContent {...{modal,setModal,role,go,d,update,state,setState,setCart,quoteOrg,setQuoteOrg,address,setAddress,busy,setBusy,startPublish,filter,setFilter,query,setQuery,priceLimit,setPriceLimit,onSignOut:signOut}}/></DialogContent></Dialog>
</div>}
