import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as { image?: string; audio_transcript?: string; user_notes?: string };
    const { image, audio_transcript, user_notes } = body;

    if (!image) {
      return NextResponse.json({ error: "No craft image provided" }, { status: 400 });
    }

    const apiKey = process.env.FACTORY_API_KEY || "";
    const baseUrl = process.env.FACTORY_API_BASE_URL || "https://openrouter.ai/api/v1";

    const prompt = `You are an expert artisan craft appraiser and cultural curator for Jungle Market (an ethical direct-to-artisan marketplace).
Analyze this craft photo and any artisan audio transcript. Extract accurate facts and return ONLY a valid JSON object with the exact keys:
{
  "title": "Descriptive, culturally respectful craft name (e.g., 'Handwoven River Bamboo Basket', 'Kondagaon Terracotta Clay Vase', 'Dokra Bell Metal Deer')",
  "category": "One of: Bamboo & cane, Terracotta clay, Tribal handloom, Dokra bell metal, Bastar wrought iron, Woodcraft & carving, Natural fibre, Forest foraged goods",
  "materials": "Comma-separated authentic raw materials (e.g., 'River bamboo, wild forest grass, mustard seed oil')",
  "length_cm": estimated length/depth in cm (number between 5 and 150),
  "width_cm": estimated width in cm (number between 5 and 150),
  "height_cm": estimated height in cm (number between 5 and 150),
  "suggested_price": fair artisan selling price in INR (number between 450 and 6500),
  "story": "A rich 2-3 sentence story describing the artisan technique, material origin, and cultural meaning.",
  "region": "Likely craft cluster in India (e.g., 'Mandla Forest Ridge, Madhya Pradesh', 'Bastar, Chhattisgarh', 'Kondagaon, Chhattisgarh', 'Dumka, Jharkhand')"
}
${audio_transcript ? `Artisan's spoken words: "${audio_transcript}"` : ""}
${user_notes ? `Artisan notes: "${user_notes}"` : ""}
Return ONLY raw JSON.`;

    const imageUrl = image.startsWith("data:") ? image : `data:image/jpeg;base64,${image}`;

    // Pipeline 1: Try Colab / Local ML Server First
    const colabBaseUrl = (process.env.COLAB_ML_URL || "http://127.0.0.1:8001").replace(/\/$/, "");
    const colabApiKey = process.env.COLAB_ML_API_KEY || "";

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 6000); // 6s timeout for ML server
      
      const mlHeaders: Record<string, string> = {
        "Content-Type": "application/json",
        "ngrok-skip-browser-warning": "true",
      };
      if (colabApiKey) {
        mlHeaders["X-ML-API-Key"] = colabApiKey;
      }

      const localResponse = await fetch(`${colabBaseUrl}/analyze`, {
        method: "POST",
        headers: mlHeaders,
        body: JSON.stringify({ image: imageUrl, audio_transcript, user_notes }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);

      if (localResponse.ok) {
        const localData = await localResponse.json();
        console.log("Successfully analyzed craft using ML model.");
        return NextResponse.json(localData);
      }
      throw new Error(`ML server failed with status ${localResponse.status}`);
    } catch (e) {
      console.warn("ML server failed or timed out. Falling back to Gemini 2.5 API...", e instanceof Error ? e.message : e);
    }

    // Pipeline 2: Fallback to Gemini via OpenRouter
    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:3000",
        "X-Title": "Jungle Market Artisan Vision"
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: imageUrl } }
            ]
          }
        ],
        max_tokens: 600,
        response_format: { type: "json_object" }
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.warn("OpenRouter API error:", response.status, errText);
      throw new Error(`OpenRouter returned ${response.status}: ${errText}`);
    }

    const data = (await response.json()) as { choices?: { message?: { content?: string } }[] };
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("No response generated by AI model");
    }

    const parsed = JSON.parse(content);
    return NextResponse.json(parsed);
  } catch (error) {
    console.error("AI craft analysis error:", error);
    return NextResponse.json({
      title: "Handcrafted Heritage Piece",
      category: "Bamboo & cane",
      materials: "Natural organic materials, forest finish",
      length_cm: 28,
      width_cm: 28,
      height_cm: 16,
      suggested_price: 1150,
      story: "Shaped by hand with traditional forest knowledge. Each subtle variation reflects patient craftsmanship and sustainable living.",
      region: "Mandla Forest Ridge, Madhya Pradesh",
      fallback: true
    });
  }
}
