"use client";
import React,{useEffect,useRef,useState} from 'react';
import {views,states,Btn,roleName} from '../jungle-market';
const critical=[
['artisan','step-1','Recording'],['artisan','step-1','Paused'],['artisan','step-1','Completed'],['artisan','step-1','Error'],['artisan','step-1','Offline'],
['artisan','step-2','Empty'],['artisan','step-2','Uploading'],['artisan','step-2','Completed'],['artisan','step-2','Replace'],['artisan','step-2','Delete'],['artisan','step-2','Error'],
['artisan','step-3','Processing'],['ambassador','inspect','Submitting'],['buyer','checkout','Payment loading'],['artisan','step-3','Partial'],['artisan','step-3','Completed'],['artisan','step-4','Error'],['artisan','step-5','Error'],['artisan','step-7','Partial'],['artisan','step-8','Error'],['artisan','step-9','Partial'],['artisan','step-9','Error'],['artisan','step-9','Disabled'],
['artisan','orders','Empty'],['artisan','orders','Error'],['artisan','wallet','Empty'],['artisan','wallet','Transfer initiated'],['artisan','wallet','Transfer success'],
['ambassador','home','Empty'],['ambassador','home','Urgent'],['ambassador','inspect','Incomplete'],['ambassador','inspect','Recording'],['ambassador','inspect','Error'],['ambassador','inspect','Rejected'],['ambassador','inspect','Success'],['ambassador','network','Search empty'],['ambassador','reports','Empty'],
['buyer','home','Loading'],['buyer','home','Empty'],['buyer','product','Low stock'],['buyer','product','Sold out'],['buyer','cart','Empty'],['buyer','checkout','Payment failure'],['buyer','checkout','Disabled'],['buyer','orders','Empty'],['buyer','orders','Delayed'],['buyer','bulk','Quote success'],['buyer','bulk','Empty']
];
const modalScenes=['roles','notifications','filters','support','quote','withdraw','cancel','revise','batch','address','certificate','qr','signout'];
const baseScenes=views.map(v=>({...v,state:'Default',modal:''}));
const scenes=[...baseScenes,...critical.map(([role,id,state])=>({role,id,state,modal:'',name:views.find(v=>v.role===role&&v.id===id)?.name||id})),...modalScenes.map(m=>({role:m==='withdraw'||m==='cancel'||m==='batch'?'artisan':m==='revise'?'ambassador':'buyer',id:m==='withdraw'?'wallet':m==='revise'?'inspect':'home',state:'Default',modal:m,name:m+' modal'})),{role:'buyer',id:'system',state:'Default',modal:'',name:'Design system foundations'}];
function path(s:any){return '/?capture=1&state='+encodeURIComponent(s.state)+(s.modal?'&modal='+s.modal:'')+'#'+s.role+'/'+s.id}
function serialize(doc:Document,width:number){const win=doc.defaultView!;const nodes:any[]=[];const components:any[]=[];const round=(n:number)=>Math.round(n*10)/10;const color=(c:string)=>c==='rgba(0, 0, 0, 0)'||c==='transparent'?null:c;const rect=(r:DOMRect)=>({x:round(r.x),y:round(r.y+win.scrollY),w:round(r.width),h:round(r.height)});
function walk(el:Element){const st=win.getComputedStyle(el),r=el.getBoundingClientRect();if(st.display==='none'||st.visibility==='hidden'||Number(st.opacity)===0||r.width<.1||r.height<.1||['SCRIPT','STYLE','LINK','META','NOSCRIPT'].includes(el.tagName)||el.matches('.skip-link,[data-sonner-toaster],.demo-strip,.design-controls,.site-footer,.support-float'))return;
const start=nodes.length;const nm=el.getAttribute('aria-label')||el.getAttribute('data-component')||el.getAttribute('data-slot')||el.classList[0]||el.tagName.toLowerCase();const common={...rect(r),name:nm,opacity:Number(st.opacity),radius:[st.borderTopLeftRadius,st.borderTopRightRadius,st.borderBottomRightRadius,st.borderBottomLeftRadius].map(parseFloat),bg:color(st.backgroundColor),border:Number.parseFloat(st.borderTopWidth)||0,borderColor:st.borderTopColor,clip:st.overflow==='hidden'};
if(el.tagName.toLowerCase()==='svg'){nodes.push({...common,type:'svg',svg:new XMLSerializer().serializeToString(el).replaceAll('currentColor',st.color)});return}
if(el.tagName==='IMG'){nodes.push({...common,type:'image',src:(el as HTMLImageElement).getAttribute('src'),fit:st.objectFit});return}
if(common.bg||common.border){nodes.push({...common,type:'rect'})}
if(st.backgroundImage!=='none'&&!common.bg)nodes.push({...common,type:'rect',bg:st.backgroundImage.includes('#')?'#0E4C3A':'rgb(14, 76, 58)'});
if(el.matches('button,a,[role="button"],[role="checkbox"],input,select,textarea')){nodes.push({...rect(r),type:'hotspot',name:(el.getAttribute('aria-label')||el.textContent||'').trim().slice(0,100),disabled:(el as HTMLButtonElement).disabled||el.getAttribute('aria-disabled')==='true'})}
if(el.matches('input,textarea,select')){let text=(el as HTMLInputElement).value||el.getAttribute('placeholder')||'';if(el.tagName==='SELECT')text=(el as unknown as HTMLSelectElement).selectedOptions[0]?.text||text;const lineWidth=r.width-parseFloat(st.paddingLeft)-parseFloat(st.paddingRight);const lines:string[]=[];if(el.tagName==='TEXTAREA'){const ctx=doc.createElement('canvas').getContext('2d')!;ctx.font=st.font;for(const para of text.split('\n')){let line='';for(const word of para.split(' ')){if(line&&ctx.measureText(line+' '+word).width>lineWidth){lines.push(line);line=word}else line+=(line?' ':'')+word}lines.push(line)}}else lines.push(text);lines.forEach((line,idx)=>{const lh=parseFloat(st.lineHeight)||20;if(line&&idx*lh<r.height-parseFloat(st.paddingTop))nodes.push({type:'text',name:nm,text:line,...rect(r),x:round(r.x+parseFloat(st.paddingLeft)),y:round(r.y+win.scrollY+parseFloat(st.paddingTop)+idx*lh),w:round(lineWidth),h:lh,font:st.fontFamily.split(',')[0].replaceAll('"','').replaceAll("'",''),size:parseFloat(st.fontSize),weight:st.fontWeight,italic:st.fontStyle==='italic',color:st.color,lh})});return}
for(const child of Array.from(el.childNodes)){if(child.nodeType===3&&child.textContent?.trim()){const tx=child.textContent;const pieces=Array.from(tx.matchAll(/\S+\s*/g));let line:any=null;for(const m of pieces){const range=doc.createRange();range.setStart(child,m.index!);range.setEnd(child,m.index!+m[0].length);const rr=range.getBoundingClientRect();if(!rr.width)continue;if(!line||Math.abs(line.y-(rr.y+win.scrollY))>3){if(line)nodes.push(line);line={type:'text',name:nm,text:m[0],...rect(rr),font:st.fontFamily.split(',')[0].replaceAll('"','').replaceAll("'",''),size:parseFloat(st.fontSize),weight:st.fontWeight,italic:st.fontStyle==='italic',color:st.color,lh:parseFloat(st.lineHeight)||parseFloat(st.fontSize)*1.2}}else{line.text+=m[0];line.w=round(rr.right-line.x)}}if(line)nodes.push(line)}else if(child.nodeType===1)walk(child as Element)}
if(el.hasAttribute('data-component')||el.matches('.jm-btn,.badge,.field,.bottom-nav,.topbar,.qr-panel,.notice,.step-capsules,.timeline,.role-options,.cart-item'))components.push({...rect(r),key:el.getAttribute('data-component')||(el.matches('.jm-btn')?'Button':el.classList[0]||nm),start,end:nodes.length});
}
Array.from(doc.body.children).forEach(walk);const height=doc.querySelector('[role=dialog]')?win.innerHeight:Math.ceil(Math.max(...nodes.filter(n=>n.y>=0).map(n=>n.y+n.h),800));return {width,height,components,nodes};}
export default function Atlas(){const [choice,setChoice]=useState(0),[width,setWidth]=useState(375),[height,setHeight]=useState(1000),[progress,setProgress]=useState(''),[running,setRunning]=useState(false),[data,setData]=useState(''),[audit,setAudit]=useState<any[]>([]);const ref=useRef<HTMLIFrameElement>(null);const captureRef=useRef<HTMLIFrameElement>(null);const [captureUrl,setCaptureUrl]=useState('about:blank');const [captureWidth,setCaptureWidth]=useState(375);
async function exported(){if(running)return;setRunning(true);setData('');const output:any[]=[];const checks:any[]=[];try{const todo=baseScenes.flatMap(s=>[375,768,1024,1440].map(w=>({s,w}))).concat(scenes.slice(baseScenes.length).map(s=>({s,w:375})));for(let i=0;i<todo.length;i++){const {s,w}=todo[i];setProgress(`${i+1} / ${todo.length} · ${s.name} · ${w}px · ${s.state}`);setCaptureWidth(w);await new Promise<void>(resolve=>setTimeout(resolve,30));const f=captureRef.current!;await new Promise<void>((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('Screen loading timed out')),25000);f.onload=()=>{clearTimeout(t);resolve()};setCaptureUrl(path(s).replace('#','&frame='+i+'#'))});await new Promise<void>(resolve=>setTimeout(resolve,180));const doc=f.contentDocument!;await doc.fonts.ready;await Promise.all(Array.from(doc.images).map(im=>im.complete?Promise.resolve():new Promise<void>(r=>{im.onload=()=>r();im.onerror=()=>r()})));await new Promise<void>(r=>setTimeout(r,80));const frame=serialize(doc,w);output.push({...s,...frame,name:`${roleName[s.role as keyof typeof roleName]} / ${s.name} / ${w} / ${s.state}`});checks.push({name:s.name,width:w,state:s.state,overflow:doc.documentElement.scrollWidth>w+1,missingImages:Array.from(doc.images).filter(im=>!im.naturalWidth).length,nodeCount:frame.nodes.length});}const result=JSON.stringify({version:1,product:'Jungle Market',frames:output,audit:checks});setData(result);setAudit(checks);setProgress(`${output.length} named frames ready · ${checks.filter(c=>c.overflow||c.missingImages).length} layout issues`)}catch(e:any){setProgress('Export paused: '+e.message)}finally{setRunning(false)}}
return <div className="atlas"><header><div className="eyebrow">JUNGLE MARKET · RESPONSIVE DESIGN ATLAS</div><h1>Every screen. One ecosystem.</h1><p>Inspect the connected prototype at each requested width, then generate the editable frame dataset.</p><div className="row"><label>Named screen<select value={choice} onChange={e=>setChoice(Number(e.target.value))}>{scenes.map((s,i)=><option value={i} key={i}>{s.role} · {s.name} · {s.state}</option>)}</select></label><label>Viewport width<select value={width} onChange={e=>setWidth(Number(e.target.value))}>{[375,768,1024,1440].map(w=><option key={w} value={w}>{w}px</option>)}</select></label><Btn onClick={exported} disabled={running}>{running?'Preparing frames…':'Prepare all named frames'}</Btn><a href="/">Return to prototype</a></div><output aria-live="polite">{progress}</output>{data&&<><a href={URL.createObjectURL(new Blob([data],{type:'application/json'}))} download="jungle-market-frames.json">Download frame dataset</a><label className="export-result">Frame dataset<textarea id="export-data" readOnly value={data}/></label><p>{audit.length} frames checked for horizontal overflow and missing imagery.</p></>}</header><div className="atlas-stage"><iframe ref={ref} title="Responsive screen preview" src={path(scenes[choice])} style={{width,height}} onLoad={()=>{setTimeout(()=>setHeight(Math.min(10000,ref.current?.contentDocument?.documentElement.scrollHeight||1000)),600)}}/></div><iframe title="Frame preparation" ref={captureRef} src={captureUrl} style={{position:'fixed',left:'-20000px',top:0,width:captureWidth,height:captureWidth<500?812:captureWidth<900?1024:900,visibility:'hidden',border:0}}/><style>{`.atlas{background:#e8e9df;min-height:100vh}.atlas>header{padding:32px;background:#faf7ee;border-bottom:1px solid #ccd3c1}.atlas h1{font-size:36px;margin:12px 0}.atlas p{font-size:13px}.atlas .row{align-items:end;margin-top:20px}.atlas label{font-size:12px;display:flex;flex-direction:column;gap:8px}.atlas select{max-width:420px}.atlas a{font-size:13px;text-decoration:underline}.atlas output{display:block;font-size:12px;margin-top:20px}.atlas-stage{overflow:auto;padding:32px;display:flex;justify-content:flex-start}.atlas-stage iframe{border:0;flex-shrink:0;background:#faf7ee;box-shadow:0 12px 50px #0a3d2e20}.export-result{margin-top:20px}.export-result textarea{height:90px;font:10px monospace;width:100%;max-width:1000px;border:1px solid #ccc}.atlas>header>p:last-child{font-size:11px}`}</style></div>}
